# Generated by Django 4.1 on 2022-08-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_grade_student_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='code',
            new_name='grade',
        ),
    ]
